all: dep1 dep2 dep3
	@echo "* Linking all objects..."

dep1: dep1.1 dep1.2
	@echo "dep1..."

dep2:
	@echo "I'm dep2"

dep3:
	@echo "I'm dep 3"

dep1.1:
	@echo "dep1.1"

dep1.2:
	@echo "dep1.2"

clean:
	@echo "Cleaning up..."
